### PR TITLE
Fix compilation failures caused by `surrealdb` API changes.

### PR DESCRIPTION
**Pull request by gibbz00**
Fixes: https://github.com/Odonno/surrealdb-migrations/issues/50

### CODE REVIEW

**Comment by dave42w** [comment]
I'd love to test this with SurrealDB beta 11. I've been out of things for a while so not sure how to get cargo to use the latest github main branch? Or are you about to do a beta11 release (given 1.0.0 due on Wed probably not worth it?)

**Comment by gibbz00** [comment]
Check out the surrealdb dependency in the cargo.toml of this repository for an example :) if assumes the default branch (main). Another example:

https://github.com/rust-lang/cargo/issues/126

**Comment by johansmitsnl** [comment]
See #53 now the 1.0.0 release is out.

**Comment by Odonno** [comment]
Thank you for your effort @gibbz00.

I am being forced to close it because #53 is already merged.

**Pull request closed without merging**
